import { Property } from "@/types/property";

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Modern Downtown Apartment",
    description:
      "Luxurious 2-bedroom apartment in the heart of downtown with stunning city views.",
    price: 450000,
    size: 95,
    bedrooms: 2,
    bathrooms: 2,
    type: "apartment",
    status: "for-sale",
    location: {
      address: "123 Main St",
      city: "New York",
      state: "NY",
      country: "USA",
      coordinates: { lat: 40.7128, lng: -74.006 },
    },
    images: [
      "https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg",
      "https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg",
      "https://images.pexels.com/photos/6782351/pexels-photo-6782351.jpeg",
    ],
    virtualTourUrl: "https://example.com/tour/1",
    vendorId: "2",
    vendorName: "Jane Smith",
    vendorContact: "+1-555-0123",
    approvalStatus: "approved",
    featured: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    title: "Spacious Family Home",
    description:
      "Beautiful 4-bedroom family home with large garden and modern amenities.",
    price: 750000,
    size: 220,
    bedrooms: 4,
    bathrooms: 3,
    type: "house",
    status: "for-sale",
    location: {
      address: "456 Oak Avenue",
      city: "Los Angeles",
      state: "CA",
      country: "USA",
      coordinates: { lat: 34.0522, lng: -118.2437 },
    },
    images: [
      "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
      "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg",
      "https://images.pexels.com/photos/2121121/pexels-photo-2121121.jpeg",
    ],
    vendorId: "2",
    vendorName: "Jane Smith",
    vendorContact: "+1-555-0124",
    approvalStatus: "approved",
    featured: true,
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "3",
    title: "Cozy Studio Apartment",
    description:
      "Perfect starter home with modern finishes and great location.",
    price: 2800,
    size: 45,
    bedrooms: 1,
    bathrooms: 1,
    type: "apartment",
    status: "for-rent",
    location: {
      address: "789 Pine Street",
      city: "Chicago",
      state: "IL",
      country: "USA",
      coordinates: { lat: 41.8781, lng: -87.6298 },
    },
    images: [
      "https://images.pexels.com/photos/2724748/pexels-photo-2724748.jpeg",
      "https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg",
    ],
    vendorId: "2",
    vendorName: "Jane Smith",
    vendorContact: "+1-555-0125",
    approvalStatus: "approved",
    featured: true,
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "4",
    title: "Executive Office Space",
    description:
      "Premium office space in business district with modern facilities.",
    price: 5500,
    size: 120,
    bedrooms: 0,
    bathrooms: 2,
    type: "office",
    status: "for-rent",
    location: {
      address: "321 Business Blvd",
      city: "San Francisco",
      state: "CA",
      country: "USA",
      coordinates: { lat: 37.7749, lng: -122.4194 },
    },
    images: [
      "https://images.pexels.com/photos/380769/pexels-photo-380769.jpeg",
      "https://images.pexels.com/photos/2883049/pexels-photo-2883049.jpeg",
    ],
    vendorId: "2",
    vendorName: "Jane Smith",
    vendorContact: "+1-555-0126",
    approvalStatus: "pending",
    featured: false,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: "5",
    title: "Development Land Plot",
    description: "Prime development land in growing suburban area.",
    price: 850000,
    size: 2000,
    bedrooms: 0,
    bathrooms: 0,
    type: "land",
    status: "for-sale",
    location: {
      address: "555 Development Road",
      city: "Austin",
      state: "TX",
      country: "USA",
      coordinates: { lat: 30.2672, lng: -97.7431 },
    },
    images: [
      "https://images.pexels.com/photos/1770809/pexels-photo-1770809.jpeg",
    ],
    vendorId: "2",
    vendorName: "Jane Smith",
    vendorContact: "+1-555-0127",
    approvalStatus: "approved",
    featured: false,
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
];

export { mockAppointments } from "./mockAppointments";
